modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://github.com/mickelus/harvests/issues/new"
license="MIT"

[[mods]]
modId="harvests"
version="${file.jarVersion}"
displayName="Scroll of Harvests"
authors="Mickelus"
description=""
credits=""
displayTest="IGNORE_ALL_VERSION"

[[dependencies.harvests]] #optional
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.harvests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,]"
    ordering="NONE"
    side="CLIENT"
[[dependencies.harvests]]
    modId="mutil"
    mandatory=true
    versionRange="[5.1.0,]"
    ordering="NONE"
    side="CLIENT"
