modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/mickelus/harvests/issues/new"
license="MIT"

[[mods]]
modId="harvests"
version="${file.jarVersion}"
displayName="Scroll of Harvests"
authors="Mickelus"
description=""
credits=""

[[dependencies.harvests]] #optional
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.harvests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="CLIENT"
[[dependencies.harvests]]
    modId="mutil"
    mandatory=true
    versionRange="[5.0.0,]"
    ordering="NONE"
    side="CLIENT"
